### ISSUE TITLE
Unable to load properly on 1.20.1 forge server

### ISSUE THREAD

**Issue by fhfzfy1231** [illucc/Kontraption#34]
**BEFORE REPORTING MAKE SURE:**
- [yes] You are on the newest version of Kontraption and Valkyrien Skies.
- [yes] You have tested it with only Kontraption, Valkyrien Skies, Mekanism and Kotlin for Forge installed.
- [yes] The bug hasn't been reported already.

**Describe the bug**
Whether using the native Forge server or the Mohist server, an InvocationTargetException:null error occurs.
![image](https://github.com/illucc/Kontraption/assets/113348942/2f8a930e-1229-4f53-aa0b-302010c3bed3)

**Expected behavior**
Logically, it should be able to start normally.

**Versions**
 - VS2 version:120-2.0.3-beta.5
 - Mekanism version: 1.20.1-10.4.8.43

**Comment by fhfzfy1231** [comment]
[crash-2024-06-18_11.20.59-fml.txt](https://github.com/user-attachments/files/15879975/crash-2024-06-18_11.20.59-fml.txt)
[debug.log](https://github.com/user-attachments/files/15879977/debug.log)
[latest.log](https://github.com/user-attachments/files/15879978/latest.log)

**Comment by arefdsg** [comment]
got same problem in singleplayer
[latest.log](https://github.com/user-attachments/files/16274573/latest.log)
[debug.log](https://github.com/user-attachments/files/16274574/debug.log)
[crash-2024-07-17_17.36.14-fml.txt](https://github.com/user-attachments/files/16274583/crash-2024-07-17_17.36.14-fml.txt)

**Comment by crlotwhite** [comment]
I got same problem.
This appears to be the main cause.

Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/LevelRenderer for invalid dist DEDICATED_SERVER

[stacktrace.txt](https://github.com/user-attachments/files/16323705/stacktrace.txt)

**Comment by crlotwhite** [comment]
oh, he already tried to solve it.  #27 
But it just dosen't upload on modrinth. 😅

**Comment by flashgnash** [comment]
Unsure if this is solved but I'm having the same issue

java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:64) ~[kfflang-4.11.0.jar%23926!/:4.11.0]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[core-47.1.47.jar%23794!/:47.1]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/LevelRenderer for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-47.1.47.jar%2351!/:47.1]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:?]
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?]
	at java.lang.Class.getConstructor(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:75) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.lambda$getListenerListInternal$0(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:61) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.LockHelper.get(LockHelper.java:44) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:39) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:50) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:276) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:252) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:244) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:199) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:193) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:187) ~[eventbus-6.0.5.jar%2355!/:?]
	at net.illuc.kontraption.Kontraption.<init>(Kontraption.kt:121) ~[kontraption-0.0.2+82af737bfe.jar%23611!/:0.0.2+82af737bfe]


seems to be the culprit, trying to run render methods on the server

**Comment by WaterOtter86** [comment]
Ima gonna look at it, today, this is latest modrich ya?

**Comment by flashgnash** [comment]
> Ima gonna look at it, today, this is latest modrich ya?

I wouldn't bother, it's the latest that's out on modrinth however I built from the latest commit in git and it's fixed now as of #27 as someone mentioned earlier in the thread

Working fine on my server now as far as I can tell

**Comment by WaterOtter86** [comment]
Great, tho probably update on modrinth is a must
